---
apiVersion: v2
name: palomar
version: 0.0.1
description: simple palomar installation
type: application

dependencies:
  - name: app-template
    alias: palomar
    version: ~4
    repository: https://bjw-s-labs.github.io/helm-charts/
